# Use admin/admin as user/password credentials
version: "3.6"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongoDb_local:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE= bestplaces
      # - MONGO_INITDB_ROOT_USERNAME= admin
      # - MONGO_INITDB_ROOT_PASSWORD= admin
    networks:
      - bestplacesdb
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    # environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME= admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD= admin
    networks:
      - bestplacesdb

networks:
  bestplacesdb:
